# -------- GENERAL --------
mode: "paper"                  # used by bot.py (realtime paper trading)
interval_seconds: 5
slippage: 0.0

# Shared symbol list for realtime (bot.py) and history download
symbols:
  - NIFTY
  - BANKNIFTY
  - RELIANCE
  - HDFCBANK
  - ICICIBANK
  - TCS
  - INFY
#  - NIFTY_FUT
#  - BANKNIFTY_FUT
#  - RELIANCE_FUT

# Capital and risk
starting_cash_realtime: 100000     # 1L TOTAL for realtime (shared across all symbols)
starting_cash_backtest: 100000     # 1L PER SYMBOL for backtest
risk_per_trade: 0.01               # 1% risk per trade

data_dir: "data"

# -------- SMARTAPI --------
smartapi:
  enable: true
  api_key: "9Ckbu4SY"
  client_id: "V54420165"
  password: "1971"
  totp_secret: "T2HSV2QXBZO3CLRB64ICLUQT5E"

  instruments:
    NIFTY:
      exchange: "NSE"
      tradingsymbol: "NIFTY 50"
      symboltoken: "99926000"
    BANKNIFTY:
      exchange: "NSE"
      tradingsymbol: "NIFTY BANK"
      symboltoken: "99926009"
    RELIANCE:
      exchange: "NSE"
      tradingsymbol: "RELIANCE-EQ"
      symboltoken: "2885"
    HDFCBANK:
      exchange: "NSE"
      tradingsymbol: "HDFCBANK-EQ"
      symboltoken: "1333"
    ICICIBANK:
      exchange: "NSE"
      tradingsymbol: "ICICIBANK-EQ"
      symboltoken: "4963"
    TCS:
      exchange: "NSE"
      tradingsymbol: "TCS-EQ"
      symboltoken: "11536"
    INFY:
      exchange: "NSE"
      tradingsymbol: "INFY-EQ"
      symboltoken: "1594"
    NIFTY_FUT:
      exchange: "NFO"
      tradingsymbol: "NIFTY27JAN26FUT"       # update monthly
      symboltoken: "49229"
    BANKNIFTY_FUT:
      exchange: "NFO"
      tradingsymbol: "BANKNIFTY27JAN26FUT"
      symboltoken: "49224"
    RELIANCE_FUT:
      exchange: "NFO"
      tradingsymbol: "RELIANCE26JANFUT"
      symboltoken: "1147579"

# -------- TELEGRAM (REALTIME BOT) --------
telegram:
  enable: true
  bot_token: "8450333553:AAEtQ7MmpDpNNbl5UxZm6UH8-7eVSo7g6tU"
  chat_ids:
    - "1210870341"
    - "641595377"
    - "570187492"
    - "792823272"
    - "1193914734"

# -------- TELEGRAM (BACKTEST BOT) --------
backtest_telegram:
  enable: true
  bot_token: "8411696443:AAENz2yoCmbgoyGXtgoc4vU-bnFCNwxQ1W0"
  chat_ids:
    - "1210870341"
    - "641595377"
    - "570187492"
    - "792823272"
    - "1193914734"

# -------- BACKTEST SETTINGS --------
backtest:
  data_dir: "data"          # where CSVs are stored
  base_year: 2018           # first year with reliable data
  months_to_run: 4          # 4 months per 6:00â€“12:00 session

