mode: paper          # keep 'paper' so ONLY PaperTrader is used

symbols:
  - NIFTY            # internal symbol key used by the bot

interval_seconds: 5  # how often to poll price / update candles (seconds)
quantity: 50         # e.g., 50 units; adjust to your simulated lot size
starting_cash: 100000
slippage: 0.0

smartapi:
  enable: true             # true = use SmartAPI for live data, false = SimulatedFeed
  api_key: "9Ckbu4SY"
  client_id: "V54420165"
  password: "Gugan_2001"
  totp: "a09f9deb-5edc-48db-b442-df25e507f142"        # or the OTP/2FA mechanism required by Angel
  exchange: "NSE"
  tradingsymbol: "NIFTY 50"  # check exact SmartAPI symbol name in Angel master list
  symboltoken: "99926000"        # numeric token for Nifty from Angel master list

telegram:
  enable: true
  bot_token: "8450333553:AAEtQ7MmpDpNNbl5UxZm6UH8-7eVSo7g6tU"
  chat_id: "1210870341"
